// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElPageHeader: typeof import('element-plus/es')['ElPageHeader']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSkeletonItem: typeof import('element-plus/es')['ElSkeletonItem']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    HomePage: typeof import('./src/components/MainViewComp/HomePage.vue')['default']
    ListCollapseSwitch: typeof import('./src/components/SideListComp/ListCollapseSwitch.vue')['default']
    LoginForm: typeof import('./src/components/TopBarComp/UserInfo/LoginForm.vue')['default']
    MainView: typeof import('./src/components/MainView.vue')['default']
    MovieDB: typeof import('./src/components/MainViewComp/MovieDB/MovieDB.vue')['default']
    MovieDetail: typeof import('./src/components/MainViewComp/MovieDetail/MovieDetail.vue')['default']
    MovieItem: typeof import('./src/components/MainViewComp/MovieDB/MovieItem/MovieItem.vue')['default']
    MovieItemList: typeof import('./src/components/MainViewComp/MovieDB/MovieItemList.vue')['default']
    MovieItemLoaded: typeof import('./src/components/MainViewComp/MovieDB/MovieItem/MovieItemLoaded.vue')['default']
    MovieItemLoading: typeof import('./src/components/MainViewComp/MovieDB/MovieItem/MovieItemLoading.vue')['default']
    PageSelector: typeof import('./src/components/MainViewComp/MovieDB/PageSelector.vue')['default']
    RegisterForm: typeof import('./src/components/TopBarComp/UserInfo/RegisterForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideList: typeof import('./src/components/SideList.vue')['default']
    TopBar: typeof import('./src/components/TopBar.vue')['default']
    UserInfo: typeof import('./src/components/TopBarComp/UserInfo.vue')['default']
  }
}
